// src/plans/index.js

/**
 * This file automatically imports all other .js files in this directory
 * and exports them as a single object.
 *
 * DO NOT EDIT THIS FILE.
 *
 * To add a new plan, create a new .js file in this directory.
 */

const modules = import.meta.glob('./!(index)*.js', { eager: true });

const allTemplates = Object.values(modules).reduce((acc, module) => {
  const plan = module.default || module;
  if (plan && plan.key) {
    acc[plan.key] = plan;
  }
  return acc;
}, {});

export const PLAN_TEMPLATES = allTemplates;
