// **Question Data**
export const themes = [
  { id: "tema1", title: "Egnethet" },
  { id: "tema2", title: "Infrastruktur og samferdsel" },
  { id: "tema3", title: "Utforming og plassering av bygg" },
  { id: "tema4", title: "Lekeplasser, natur- og grøntområder" },
  { id: "tema5", title: "Barn og unges interesser" },
  { id: "tema6", title: "Universell utforming og tilgjengelighet" },
  { id: "tema7", title: "Vann og avløp" },
  { id: "tema8", title: "Rekkefølgekrav" },
  { id: "tema9", title: "Kvalitet på plan og kunnskapsgrunnlag" },
];

// **Question List**
export const questions = [
  //Tema 1 Egnethet
  { id: "q1", theme: "tema1", text: "I hvilke grad har området en god økonomisk forutsetning for å realisere et boligprosjekt?" },
  { id: "q2", theme: "tema1", text: "Hvilke påvirkning vil tiltaket ha på dyrket og dyrkbar mark?" },
  { id: "q3", theme: "tema1", text: "Hvilke påvirkning vil tiltaket ha for urørt natur og dyreliv?" },
  { id: "q4", theme: "tema1", text: "Hvilke påvirkning vil tiltaket ha på omkringliggende områder?" },
  { id: "q5", theme: "tema1", text: "Er adkomst til området enkelt for tiltenkte brukergrupper i dag?" },
  { id: "q6", theme: "tema1", text: "I hvilke grad er nødvendige servicetilbud tilgjengelige fra området?" },
  { id: "q7", theme: "tema1", text: "I hvilke grad ligger området i tilstrekkelig nærhet til grøntstrukturer og rekreasjonsområder?" },
  { id: "q8", theme: "tema1", text: "I hvilke grad ligger prosjektet innenfor et prioritert vekstområde?" },
  { id: "q9", theme: "tema1", text: "Hvordan kan en utbygging påvirke kutlurminner og kulturmiljø?" },
  { id: "q10", theme: "tema1", text: "Dersom området skal transformeres, i hvilke grad er området modent for en transformasjon?" },
  { id: "q11", theme: "tema1", text: "I hvilke grad egner området seg for boligbebyggelse kontra andre arealformål, da også nullalternativ?" },
  { id: "q12", theme: "tema1", text: "Er utgangspunktet godt for å oppnå gode støyforhold?" },
  { id: "q13", theme: "tema1", text: "Er utgangspunktet godt for å oppnå gode sol- og lysforhold?" },
  { id: "q14", theme: "tema1", text: "Har tiltenkt område god tilknytning til nødvendig grad av kollektivtrafikk?" },
  { id: "q15", theme: "tema1", text: "I hvike grad kan transport til planområdet løses med sykkel, gange og kollektivtrafikk fremfor bil?" },
  { id: "q16", theme: "tema1", text: "Har terreng et godt utgangspunkt for å oppnå god tilgjengelighet?" },
  { id: "q17", theme: "tema1", text: "Har terreng et godt utgangspunkt for å realisere et boligprosjekt med tilhørende funksjoner?" },
  //Tema 2 Infrastruktur og samferdsel
  { id: "q18", theme: "tema2", text: "I hvilke grad sikres det en tilstrekkelig veistandard til boligene fra omkringliggende områder og målpunkt?" },
  { id: "q19", theme: "tema2", text: "I hvilke grad sikres gode løsninger på infrastruktur for myke trafikanter fra boligene til målpunkt, servicetilbud og grøntstrukturer?" },
  { id: "q20", theme: "tema2", text: "Får interne bevegelseslinjer for myke trafikanter tilstrekkelig kvalitet med tanke på utforming, plassering, tiltenkt bruk og sikkerhet?" },
  { id: "q21", theme: "tema2", text: "Er interne bevegelseslinjer for myke trafikanter tilstrekkelig prioritert for å skape logiske og attraktive traseer " },
  { id: "q22", theme: "tema2", text: "Sikres det et hensiktsmessig antall parkeringsplasser?" },
  { id: "q23", theme: "tema2", text: "Sikres det tilstrekkelig kvalitet for utforming og lokalisering av parkeringsløsninger?" },
  { id: "q24", theme: "tema2", text: "Sikres det tilstrekkelig antall sykkelparkeringsplasser?" },
  { id: "q25", theme: "tema2", text: "Sikres det tilstrekkelig kvalitet med tanke på utforming og lokalisering av sykkelparkeringsplasser?" },
  { id: "q26", theme: "tema2", text: "I hvilke grad får boligene en hensiktsmessig kollektivdekning?" },
  { id: "q27", theme: "tema2", text: "I hvilken grad er kollektivtilbud tilgjengelig og attraktiv som transportvalg?" },
  //Tema 3 Utforming og plassering av bygg
  { id: "q28", theme: "tema3", text: "Sikres det en god estetisk kvalitet?" },
  { id: "q29", theme: "tema3", text: "Hvilke påvirkning vil byggverks utforming og estetiske kvaliteter ha for tilgrensende områder, deriblant også sol- og lysforhold? " },
  { id: "q30", theme: "tema3", text: "Hvilke fjernvirkninger vil bygg gi?" },
  { id: "q31", theme: "tema3", text: "Har planen en hensiktsmessig utnyttelsesgrad ut fra områdets tåleevne?" },
  { id: "q32", theme: "tema3", text: "Har planen en hensiktsmessig utnyttelsesgrad gitt plassering og tilpasning til omkringliggende bebyggelse?" },
  { id: "q33", theme: "tema3", text: "Har man lagt til rette for en hensiktsmessig utnytting gitt planlagt fremtidig bruk av tilgrensende områder?" },
  { id: "q34", theme: "tema3", text: "Er planlagte bygg godt tilpasset eksisterende landskap og bebyggelse?" },
  { id: "q35", theme: "tema3", text: "Er det sikret en variert og hensiktsmessig boenhetsfordeling med tanke på størrelser?" },
  { id: "q36", theme: "tema3", text: "Ser boenheter ut til å få en god kvalitet og funksjonalitet?" },
  { id: "q37", theme: "tema3", text: "Sikres gode private uteoppholdsareal tilknyttet boenhetene?" },
  { id: "q38", theme: "tema3", text: "I hvilke grad har planen en riktig boligtetthet og boligsammensetning basert på planområdets plassering?" },
  { id: "q39", theme: "tema3", text: "I hvilke grad er det tenkt på og avsatt areal til nødvendige servicebygg som f.eks trafo?" },
  { id: "q40", theme: "tema3", text: "Sikres det i nødvendig grad felles innendørs oppholdsareal av god kvalitet med hensiktsmessige funksjoner?" },
  { id: "q41", theme: "tema3", text: "Oppnås det et godt samspill mellom bygg og andre funksjoner som parkering og uteoppholdsareal?" },
  { id: "q42", theme: "tema3", text: "I hvilke grad er bygg plassert på en slik måte at man oppnår et godt samspill med andre bygg, uteareal, naturelementer, traseer, overvannsløsninger osv.?" },
  { id: "q43", theme: "tema3", text: "I hvilke grad sikres matrial og fargevalg av god kvalitet?" },
  //Tema 4 Natur- og grøntområder
  { id: "q44", theme: "tema4", text: "Settes det av nødvendige landskaps- og terrengbuffere mot tilgrensende funksjoner og urørt natur?" },
  { id: "q45", theme: "tema4", text: "Har man beholdt eksisternde natur- og landskapsdrag, samt terrengformasjoner, trær og vann i dagen med særlig verdi?" },
  { id: "q46", theme: "tema4", text: "Har man uavhengig av naturverdi beholdt tilstrekkelig med naturelementer og områder som ikke bearbeides for å gjøre området attraktivt og gi muligheter for naturlig lek og opphold?" },
  { id: "q47", theme: "tema4", text: "Er det avsatt gode grøntområder med tanke på plassering, kvalitet og funksjon?" },
  { id: "q48", theme: "tema4", text: "Sikres en hensiktsmessig opparbeiding og beplantning av arealene?" },
  { id: "q49", theme: "tema4", text: "Er det gode synergier mellom overvanns- og flomhåndtering og grøntområder?" },
  { id: "q50", theme: "tema4", text: "I hvilke grad oppnår planen en god balanse mellom private, halvprivate og offentlige areal?" },
  { id: "q51", theme: "tema4", text: "Har man utredet og beholdt eventuelle stier og grøntdrag som går gjennom planområdet?" },
  { id: "q52", theme: "tema4", text: "Skapes det gode og naturlige bevegelseslinjer gjennom planområdet, som i nødvendig grad kan brukes av alle?" },
  { id: "q53", theme: "tema4", text: "Er det sikret tilstrekkelig belysning i traseer som etableres gjennom planområdet?" },
  { id: "q54", theme: "tema4", text: "Foreligger det rødlistede arter innenfor planområdet, om ja, hvordan er ivaretagelsen av artene?" },
  //Tema 5 Barn og unges interesser
  { id: "q55", theme: "tema5", text: "Er det avsatt tilstrekkelige uteareal til barn- og unge som er tilgjenglig for alle?" },
  { id: "q56", theme: "tema5", text: "Får eventuelle private uteoppholdsareal gode premisser for bruk av barn og unge?" },
  { id: "q57", theme: "tema5", text: "Sikres viktige natur- og terrengformasjoner som kan være attraktive for barn og unge?" },
  { id: "q58", theme: "tema5", text: "Sikres det gode lekeplasser og grøntområder med tanke på størrelse, varierte funksjoner og lek?" },
  { id: "q59", theme: "tema5", text: "Gis arealene en attraktiv plassering med gode støy og lysforhold?" },
  { id: "q60", theme: "tema5", text: "Sikres sittegrupper og voksenfunksjoner som kan kombineres med lek?" },
  { id: "q61", theme: "tema5", text: "Sikres sammenhengende bevegelseslinjer til målpunkt som er trafikksikre og attraktive?" },
  { id: "q62", theme: "tema5", text: "Oppnås det tilstrekkelig trafikksikkerhet utad og intern i planområdet?" },
  { id: "q63", theme: "tema5", text: "Oppnås det tilstrekkelig sikkerhet for å unngå uønsket og farlig bruk av barn og unge?" },
  { id: "q64", theme: "tema5", text: "Er det sikret tilstrekkelig belysning i traseer som etableres gjennom planområdet?" },
  //Tema 6 Universell utforming og tilgjengelighet
  { id: "q65", theme: "tema6", text: "Er området tilgjengelig og forståelig for myke trafikanter med funksjonsnedsettelser?" },
  { id: "q66", theme: "tema6", text: "I hvilke grad kan man si at legges tilrette for alle aldersgrupper og familiesammensetninger?" },
  { id: "q67", theme: "tema6", text: "Er det sikret gode leke og uteoppholdsmuligheter for mennesker med funksjonsvariasjoner?" },
  { id: "q68", theme: "tema6", text: "Sikres det et hensiktsmessig antall UU- og tilgjengelige boliger?" },
  { id: "q69", theme: "tema6", text: "Er det gjort en analyse på tiltak som bør gjøres for å oppnå tilgjenglighet for prosjektet?" },
  { id: "q70", theme: "tema6", text: "Er det utarbeidet konkrete bestemmelser som tar for seg prioriterte forhold for å oppnå UU der det er nødvendig?" },
  //Tema 7 Vann og avløp
  { id: "q71", theme: "tema7", text: "I hvilke grad sikres det at overvann håndteres internt på planområdet og at tiltaket ikke fører til en økt påkjenning på tilgrensende områder?" },
  { id: "q72", theme: "tema7", text: "I hvilken grad forbedres overvannsituasjonen i forhold til dagens situasjon?" },
  { id: "q73", theme: "tema7", text: "I hvilke grad er løsninger for overvann prosjektert og gjennomførbare?" },
  { id: "q74", theme: "tema7", text: "I hvilke grad brukes overvannssystemer for å oppnå synergier med natur og grøntområder?" },
  { id: "q75", theme: "tema7", text: "Sikres nødvendige flomveier og får de en funksjon utover at det er flomveier?" },
  { id: "q76", theme: "tema7", text: "I hvilke grad har planen fokus på permamble flater, grønne tak m.m? Har man en bevisst tilnærming for å unngå harde flater som bidrar til økt overvann?" },
  { id: "q77", theme: "tema7", text: "I hvilke grad er nødvendige traseer for vann og avløpsledninger kartlagt? Hvilke konsekvenser vil etablering av ledningsnettet ha for området?" },
  { id: "q78", theme: "tema7", text: "Får vann og avløpsledninger nødvendige dimensjoner til å sikre en helhetlig utvikling?" },
  //Tema 8 Rekkefølgekrav
  { id: "q79", theme: "tema8", text: "I hvilke grad sikres rekkefølgekrav for nødvendig omkringliggende infrastruktur gjennom planen?" },
  { id: "q80", theme: "tema8", text: "I hvilke grad sikres rekkefølgekrav for nødvendig infrastruktur for vann, overvann og flom?" },
  { id: "q81", theme: "tema8", text: "I hvilke grad sikres rekkefølgekrav for nødvendige grøntområder, grøntdrag, lekeplasser m.m?" },
  { id: "q82", theme: "tema8", text: "I hvilke grad sikres rekkefølgekrav for ønsket utbyggingsrekkefølge?" },
  { id: "q83", theme: "tema8", text: "I hvilke grad sikres andre nødvendige rekkefølgekrav for prosjektet?" },
  //Tema 9 Kvalitet på plan og kunnskapsgrunnlag
  { id: "q84", theme: "tema9", text: "Foreligger det et nødvendig kunnskapsgrunnlag for å kunne sette gode rekkefølgekrav?" },
  { id: "q85", theme: "tema9", text: "Foreligger det et nødvendig kunnskapsgrunnlag for å oppnå tilstrekkelig sikkerhet for planområdet og omkringliggende områder?" },
  { id: "q86", theme: "tema9", text: "Foreligger det et nødvendig kunnskapsgrunnlag for å kunne vurdere og ivareta natur-, kultur-, og miljøinteresser?" },
  { id: "q87", theme: "tema9", text: "Foreligger det et nødvendig kunnskapsgrunnlag for å kunne vurdere en helhetlig utvikling av feltet sammen med omkringliggende områder og samlet potensielt utviklingspotensial?" },
  { id: "q88", theme: "tema9", text: "I hvilke grad er plankart tilstrekkelig detaljert for å sikre planens intensjoner og kvaliteter?" },
  { id: "q89", theme: "tema9", text: "I hvilke grad er bestemmelser i nødvendig grad konkrete og i nødvendig grad dekkende for å sikre planens intensjoner og kvaliteter?" },
  { id: "q90", theme: "tema9", text: "Er det i stor grad samsvar mellom ikke juridiske og juridisk bindende dokumenter og illustrasjoner?" }
];

// **Priority Multipliers (Unique per Question)**
export const questionMultipliers = {
  //Tema 1 Egnethet
  q1: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q2: { Lav: 1, Normal: 1.4, Høy: 1.8, "Ikke aktuelt": 1 },
  q3: { Lav: 1, Normal: 1.4, Høy: 1.8, "Ikke aktuelt": 1 },
  q4: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q5: { Lav: 0.6, Normal: 0.8, Høy: 1, "Ikke aktuelt": 1 },
  q6: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q7: { Lav: 0.8, Normal: 1.1, Høy: 1.3, "Ikke aktuelt": 1 },
  q8: { Lav: 0.8, Normal: 1.1, Høy: 1.4, "Ikke aktuelt": 1 },
  q9: { Lav: 0.6, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q10: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q11: { Lav: 0.8, Normal: 1.1, Høy: 1.3, "Ikke aktuelt": 1 },
  q12: { Lav: 0.5, Normal: 0.8, Høy: 1, "Ikke aktuelt": 1 },
  q13: { Lav: 0.6, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q14: { Lav: 0.7, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q15: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q16: { Lav: 0.6, Normal: 0.8, Høy: 1, "Ikke aktuelt": 1 },
  q17: { Lav: 0.5, Normal: 0.9, Høy: 1.3, "Ikke aktuelt": 1 },
  //Tema 2 Infrastruktur og samferdsel
  q18: { Lav: 0.7, Normal: 1, Høy: 1.3, "Ikke aktuelt": 1 },
  q19: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q20: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q21: { Lav: 0.7, Normal: 1, Høy: 1.3, "Ikke aktuelt": 1 },
  q22: { Lav: 0.6, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q23: { Lav: 0.8, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q24: { Lav: 0.7, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q25: { Lav: 0.6, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q26: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q27: { Lav: 0.6, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  //Tema 3 Utforming og plassering av bygg
  q28: { Lav: 0.7, Normal: 1.1, Høy: 1.4, "Ikke aktuelt": 1 },
  q29: { Lav: 0.5, Normal: 1, Høy: 1.5, "Ikke aktuelt": 1 },
  q30: { Lav: 0.4, Normal: 0.8, Høy: 1.2, "Ikke aktuelt": 1 },
  q31: { Lav: 0.8, Normal: 1.1, Høy: 1.4, "Ikke aktuelt": 1 },
  q32: { Lav: 0.8, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q33: { Lav: 0.6, Normal: 1, Høy: 1.3, "Ikke aktuelt": 1 },
  q34: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q35: { Lav: 0.5, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q36: { Lav: 0.5, Normal: 1, Høy: 1.3, "Ikke aktuelt": 1 },
  q37: { Lav: 0.5, Normal: 0.8, Høy: 1, "Ikke aktuelt": 1 },
  q38: { Lav: 0.6, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q39: { Lav: 0.6, Normal: 0.8, Høy: 1, "Ikke aktuelt": 1 },
  q40: { Lav: 0.6, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q41: { Lav: 0.6, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q42: { Lav: 0.8, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q43: { Lav: 0.6, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  //Tema 4 Natur- og grøntområder
  q44: { Lav: 0.6, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q45: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q46: { Lav: 0.6, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q47: { Lav: 0.9, Normal: 1.2, Høy: 1.6, "Ikke aktuelt": 1 },
  q48: { Lav: 0.5, Normal: 0.8, Høy: 1, "Ikke aktuelt": 1 },
  q49: { Lav: 0.5, Normal: 0.9, Høy: 1.2, "Ikke aktuelt": 1 },
  q50: { Lav: 0.8, Normal: 1, Høy: 1.3, "Ikke aktuelt": 1 },
  q51: { Lav: 0.5, Normal: 0.8, Høy: 1.1, "Ikke aktuelt": 1 },
  q52: { Lav: 0.8, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q53: { Lav: 0.4, Normal: 0.7, Høy: 1, "Ikke aktuelt": 1 },
  q54: { Lav: 0.7, Normal: 1.1, Høy: 1.5, "Ikke aktuelt": 1 },
  //Tema 5 Barn og unges interesser
  q55: { Lav: 1, Normal: 1.2, Høy: 1.4, "Ikke aktuelt": 1 },
  q56: { Lav: 0.6, Normal: 0.8, Høy: 1, "Ikke aktuelt": 1 },
  q57: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q58: { Lav: 1, Normal: 1.2, Høy: 1.6, "Ikke aktuelt": 1 },
  q59: { Lav: 0.9, Normal: 1.1, Høy: 1.4, "Ikke aktuelt": 1 },
  q60: { Lav: 0.7, Normal: 0.9, Høy: 1.1, "Ikke aktuelt": 1 },
  q61: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q62: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q63: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q64: { Lav: 0.6, Normal: 0.8, Høy: 1, "Ikke aktuelt": 1 },
  //Tema 6 Universell utforming og tilgjengelighet
  q65: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q66: { Lav: 0.6, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q67: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q68: { Lav: 1, Normal: 1.2, Høy: 1.4, "Ikke aktuelt": 1 },
  q69: { Lav: 0.6, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q70: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  //Tema 7 Vann og avløp
  q71: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q72: { Lav: 0.6, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q73: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q74: { Lav: 0.5, Normal: 0.9, Høy: 1.1, "Ikke aktuelt": 1 },
  q75: { Lav: 0.6, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q76: { Lav: 0.8, Normal: 1, Høy: 1.4, "Ikke aktuelt": 1 },
  q77: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q78: { Lav: 0.6, Normal: 1, Høy: 1.1, "Ikke aktuelt": 1 },
  //Tema 8 Rekkefølgekrav
  q79: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q80: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q81: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q82: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q83: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  //Tema 9 Kvalitet på plan og kunnskapsgrunnlag
  q84: { Lav: 0.8, Normal: 1, Høy: 1.2, "Ikke aktuelt": 1 },
  q85: { Lav: 1, Normal: 1.2, Høy: 1.4, "Ikke aktuelt": 1 },
  q86: { Lav: 1, Normal: 1.2, Høy: 1.4, "Ikke aktuelt": 1 },
  q87: { Lav: 1, Normal: 1.2, Høy: 1.4, "Ikke aktuelt": 1 },
  q88: { Lav: 1, Normal: 1.2, Høy: 1.4, "Ikke aktuelt": 1 },
  q89: { Lav: 1, Normal: 1.2, Høy: 1.4, "Ikke aktuelt": 1 },
  q90: { Lav: 1, Normal: 1.2, Høy: 1.4, "Ikke aktuelt": 1 }
};